[features]
seeds = false
[programs.localnet]
calculator_dapp = "8UsT1RSVr7mYLPfMQ6FB6y5PhtW9ugXXuK7p5KoqMW9N"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/beekay/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
